# Generated by Django 4.1.7 on 2023-03-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
                ('time_estimated', models.IntegerField()),
                ('state', models.CharField(choices=[('success', 'success'), ('failure', 'failure'), ('in_progress', 'in_progress')], max_length=20)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.user')),
            ],
        ),
    ]
